version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.presentation.api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      
  consumer:
    build: .
    command: faststream run app.presentation.consumers.app:app
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db

  outbox_workers:
    build: .
    command: python -m app.presentation.workers.main
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16
    container_name: payments_db
    restart: always
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password